import { notFound } from "next/navigation";
import { prisma } from "@/lib/prisma";
import { createWhatsAppLink } from "@/lib/whatsapp";

export default async function CustomerPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const customer = await prisma.customer.findUnique({ where: { id }, include: { packages: { include: { service: true, treatments: { orderBy: { sessionNumber: "asc" } } } }, appointments: { orderBy: { scheduledAt: "desc" }, include: { package: { include: { service: true } } } } } });
  if (!customer) notFound();
  const nextAppointment = customer.appointments.find((a) => a.scheduledAt > new Date() && a.status !== "CANCELLED");
  return <div className="space-y-6"><div className="flex items-start justify-between"><div><h1 className="text-2xl font-bold">{customer.name}</h1><p className="text-sm text-slate-500">{customer.phone}</p></div><a href={createWhatsAppLink(customer.phone, `Hi ${customer.name} 👋`)} target="_blank" rel="noreferrer" className="rounded-lg bg-green-600 px-4 py-2 text-sm font-medium text-white">WhatsApp</a></div><section className="rounded-xl border bg-white p-5"><h2 className="font-semibold">Active packages</h2><div className="mt-4 space-y-4">{customer.packages.map((pkg) => { const remaining = pkg.totalSessions - pkg.treatments.length; return <div key={pkg.id} className="rounded-lg border p-4"><div className="flex justify-between"><div><p className="font-medium">{pkg.service.name}</p><p className="text-sm text-slate-500">Purchased {pkg.purchaseDate.toLocaleDateString()}</p></div><span className="text-sm font-medium">{remaining} remaining</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full bg-slate-900" style={{ width: `${Math.min(100, (pkg.treatments.length / pkg.totalSessions) * 100)}%` }} /></div><p className="mt-2 text-xs text-slate-500">{pkg.treatments.length} / {pkg.totalSessions} sessions completed</p></div>})}{customer.packages.length === 0 && <p className="text-sm text-slate-500">No packages.</p>}</div></section><section className="rounded-xl border bg-white p-5"><h2 className="font-semibold">Next appointment</h2>{nextAppointment ? <div className="mt-4"><p className="font-medium">{nextAppointment.scheduledAt.toLocaleString()}</p><p className="text-sm text-slate-500">{nextAppointment.package?.service.name ?? "Treatment"} · {nextAppointment.status}</p></div> : <p className="mt-4 text-sm text-amber-700">No upcoming appointment.</p>}</section><section className="rounded-xl border bg-white p-5"><h2 className="font-semibold">Treatment history</h2><div className="mt-4 divide-y">{customer.packages.flatMap((pkg) => pkg.treatments.map((t) => <div key={t.id} className="flex justify-between py-3"><span>Session {t.sessionNumber} · {pkg.service.name}</span><span className="text-sm text-slate-500">{t.treatmentDate.toLocaleDateString()}</span></div>))}</div></section></div>;
}
